# Generated by Django 5.0.7 on 2024-08-01 01:06

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('year_published', models.IntegerField(choices=manager.models.year_choices, default=manager.models.current_year, verbose_name='year')),
                ('summary', models.TextField(max_length=2000)),
            ],
        ),
    ]
